### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by akalicki** [odds-lang/odds#105]
Handle the same way we do list cons, in the analyzer as a function

**Comment by dannyech** [comment]
let's make it a builtin function - want to avoid adding any more operators; we already have a ton.

**Comment by akalicki** [comment]
sounds good to me!

**Comment by alexandramedway** [comment]
added to "better_syntactic_sugar" branch

**Comment by dannyech** [comment]
@alexandramedway see comment i made on commit - need to remove 2 lines
