### ISSUE TITLE
Hack the analyzer to constrain types on stdlib list functions.

### ISSUE THREAD

**Issue by dannyech** [odds-lang/odds#109]
@akalicki Right now we are hacking the analyzer to infer and constrain types on `cons`.

Should we do the same for the other stdlib list functions?

**Comment by akalicki** [comment]
`cons` isn't a stdlib function, it's a builtin which is why we are doing it. I think it's better to have cases our analyzer doesn't handle then build in functionality for an arbitrary subset of functions

**Comment by dannyech** [comment]
ok!
