### ISSUE TITLE
Picture to come 

### ISSUE THREAD

**Issue by dannyech** [odds-lang/odds#111]
Sushi

**Comment by dannyech** [comment]
https://www.quora.com/

**Comment by lillyfwang** [comment]
![wut](http://vignette4.wikia.nocookie.net/walkingdead/images/3/34/Wut......jpg/revision/latest?cb=20131121222224)

**Comment by akalicki** [comment]
![sushi](http://24.media.tumblr.com/4eb381522eb7aa20c6830da8f0f4d309/tumblr_myr8xq0UTe1qjeu0to1_1280.gif)

**Comment by akalicki** [comment]
![eyebrow](http://i.imgur.com/Ht9kAWE.gif)
