### ISSUE TITLE
Dress Code

### ISSUE THREAD

**Issue by dannyech** [odds-lang/odds#144]
![edwards](https://cloud.githubusercontent.com/assets/12707525/11919068/0383af66-a716-11e5-9ca5-a922d34b5a7a.jpg)

**Comment by dannyech** [comment]
expect to receive that smile if we are received wearing those clothes

**Comment by dannyech** [comment]
@akalicki @lillyfwang @alexandramedway

**Comment by akalicki** [comment]
does anyone have an extra polo button-down I can borrow? @dannyech

**Comment by dannyech** [comment]
ahhh i only have one - i think i'm going to wear a Tee-shirt b/c he often wears these bright tee-shirts
