### ISSUE TITLE
Anon function "caking"

### ISSUE THREAD

**Issue by akalicki** [odds-lang/odds#75]
Allow simultaneous definition and calling of anonymous functions, e.g.
```
do (() -> return print("Hello, World!"))()
```

**Comment by lillyfwang** [comment]
![let's get...](http://i939.photobucket.com/albums/ad235/GetCaking/cakebutton.jpg)
![CAKING!](https://45.media.tumblr.com/c28d4c3b90960b34b23d7b9ff075ab8b/tumblr_mgod7ugtRa1rvvqj8o1_500.gif)

**Comment by akalicki** [comment]
CAKING! @alexandramedway @dannyech

**Comment by dannyech** [comment]
mmmmmmmm
