### ISSUE TITLE
Standard library: print() should return void

### ISSUE THREAD

**Issue by akalicki** [odds-lang/odds#76]
Every statement in our language should return something - we say `print` returns `void`. But in Python, `print` isn't allowed to return anything. So a function like
```
do () -> return print("Hello")
```
is valid in our language but will throw an error in Python. Any ideas for a way to wrap the print function (standard library? wrap in Python?) to return `None` in our compiled code?

**Comment by dannyech** [comment]
yeah this shouldn't be too hard - just write a wrapper for print that always returns something
