### ISSUE TITLE
Return Type mismatch

### ISSUE THREAD

**Issue by dannyech** [odds-lang/odds#79]
@akalicki - we were talking about this earlier.

**Comment by dannyech** [comment]
Check to see if there is a return type mismatch at the end of check_f_decl, if so throw an error

**Comment by akalicki** [comment]
```
do f = (g, x) ->
    do !g(2)
    return g(x) + 3
```
should fail

**Comment by akalicki** [comment]
Edit @dannyech: the above code fails as expected in the analyzer. What was the example we're not handling again?

**Comment by dannyech** [comment]
@akalicki The issue was on recursion:

```ocaml
do f = (x) ->
  do !f(2)
  return 2
```
passes. But the above should fail.

I believe the issue is only in how we are handling the return because:
```ocaml
do f = (x) ->
  do !f(2)
  do f(2) + 2
  return 2
```
does fail (as it should)
