### ISSUE TITLE
Serious Issue with Constraint System - Unsure How to Fix. Require Overhaul?

### ISSUE THREAD

**Issue by dannyech** [odds-lang/odds#80]
```ocaml
do call = (f, x) ->
  do f(x)
  do f(2)
  return ... (*doesn't matter*)
```

Because `x` is fed to `f` **before** `2` is fed to `f`, `x` is not constrained. The Analyzer thinks its type is `Any`.

However, `x` ought to be constrained to a `Num`. If `x` is a non-Num, our analyzer will not catch the type error, and there will be a runtime error. This is bad. To constrain `x`, we would somehow need to remember that it is being called in `f`, and that `f` is eventually be constrained. Unsure how we would go about fixing this problem... 
@akalicki 

This is why ocaml has `a'` and `b'` and `c'` etc...

**Comment by akalicki** [comment]
I don't think we can handle this without a major rework of our constraint system. I'm inclined to say we let this be a runtime error. Not ideal, but it's better to not catch some cases than have our compiler reject valid ones. I think the effort that'd be needed to handle this is probably not worth it considering the other stuff we have to do.

Thoughts?

**Comment by dannyech** [comment]
Agreed - I talked to @alexandramedway yesterday too, and I think she would agree w/ you as well. If we have time, perhaps we can fix it...

**Comment by akalicki** [comment]
closing for now, can reopen if we want to come back to it
